// Code generated by "stringer -type=PathType -linecomment"; DO NOT EDIT.

package spiffy

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PathMoveToAbs-0]
	_ = x[PathMoveToRel-1]
	_ = x[PathLineToAbs-2]
	_ = x[PathLineToRel-3]
	_ = x[PathLineToHorizontalAbs-4]
	_ = x[PathLineToHorizontalRel-5]
	_ = x[PathLineToVerticalAbs-6]
	_ = x[PathLineToVerticalRel-7]
	_ = x[PathCubicBezierCurveAbs-8]
	_ = x[PathCubicBezierCurveRel-9]
}

const _PathType_name = "MmLlHhVvCc"

var _PathType_index = [...]uint8{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

func (i PathType) String() string {
	if i < 0 || i >= PathType(len(_PathType_index)-1) {
		return "PathType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PathType_name[_PathType_index[i]:_PathType_index[i+1]]
}
